name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend-service-central
            git pull
            echo "$ENV_FILE" > .env
            sudo docker-compose down
            sudo docker-compose up -d --build
          envs: ENV_FILE
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
